;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  COMMON.INC                                ;
;                                   EE/CS 51                                 ;
;                    Include file for commonly used constants                ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains commonly used constants. 

; Word and byte size:

WORDSIZE        EQU         0002H       ; 1 word is 2 bytes
BYTESIZE        EQU         0001H       ; 1 byte is 1 byte 