;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                  COMMON.INC                                ;
;                                   EE/CS 51                                 ;
;                    Include file for commonly used constants                ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains commonly used constants. 

; Word and byte size:

WORDSIZE        EQU         2
BYTESIZE        EQU         1