;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                       Event handlers for remote unit                       ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



MAX_DISPLAY_STR_SIZE        EQU         64          ; 64 characters
MAX_COMMAND_STR_SIZE        EQU         8           ; V+65534, for example 
NO_EVENT_VAL 				EQU 		0FFFFH 		